name: Unity

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./NcmbFcmPlugin/gradlew build
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v2.0-alpha-4
