name: Unity

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./NcmbFcmPlugin/gradlew build
      - name: Test
        run: ./NcmbFcmPlugin/gradlew test --stacktrace
